# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under mlops_dbx/resources/*
# and mlops_dbx/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for mlops_dbx Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./mlops_dbx

env:
  DATABRICKS_AUTH_TYPE: oauth-m2m
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
  DATABRICKS_CLIENT_SECRET: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: mlops_dbx-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.236.0
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t staging
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t staging
